### ISSUE TITLE
Circular dependencies with cmsis-core

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/cmsis-core-k64f#6]
Is it intentional that cmsis-core-k64f depends on cmsis-core? This creates a dependency loop, which makes it hard to make yotta use forked modules without forking the complete dependency tree.

At the moment the dependencies are:

```
\_ cmsis-core
  \_ cmsis-core-freescale
    \_ cmsis-core-k64f
       \_ cmsis-core
```

Shouldn't be it:

```
\_ cmsis-core
  \_ cmsis-core-freescale
    \_ cmsis-core-k64f
```

Then I could reversely depend in my application's module.json

```
      "cmsis-core-k64": "other-github-repo/cmsis-core-k64#master",
      "cmsis-core-freescale": "other-github-repo/cmsis-core-freescale#master",
```

without having to touch cmsis-core or rewriting each and every module.json of the various modules.

**Comment by 0xc0170** [comment]
@markus-becker-tridonic-com Have you tried to remove that dependency and build this module ? It should fail, as there are dependencies on cmsis-core.

Cmsis-core defines target dependencies, you need to fork it anyway.

**Comment by markus-becker-tridonic-com** [comment]
Haven't tried to build it yet. So yes, most likely it will fail.

If cmsis-core needs to be forked as well, it really gets hard to add additional targets from the outside of ARM that are part of a family that is already present and mix it with modules from yotta. Any suggestions?

**Comment by 0xc0170** [comment]
> If cmsis-core needs to be forked as well, it really gets hard to add additional targets from the outside of ARM that are part of a family that is already present and mix it with modules from yotta. Any suggestions?

Can you elaborate? mainly: "the outside of ARM that are part of a family"

**Comment by markus-becker-tridonic-com** [comment]
Currently, there is ST429 in yotta. We are working on a different F4, which we would like to upstream, but during development, we need to reference them in module.json without touching each and every module from the bottom of the dependency tree to the top.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-911

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1019

**Comment by autopulated** [comment]
Closing this as there's no way to remove the circular dependency with the current design for CMSIS.
